### ISSUE TITLE
I have a question regarding data preprocessing.

### ISSUE THREAD

**Issue by jp1924** [mkunes/w2v2_audioFrameClassification#2]
Hello,  
I raise the issue because I have a question during data preprocessing.

fisrt.
How should I run the matlab file? Should I run it using octave-cli in ubuntu?

second.
There is a parameter called dir_ref_in in the prepare_data_for_wav2vec.m file, but I don't know which one to put in here. Should I insert a file path in txt format like wavListFile?

**Comment by mkunes** [comment]
Hi, thanks for taking an interest.

We only used MATLAB. But I've just gone through the code and checked it in Octave too. It needed a few tweaks (some unsupported functions, etc.), but it should work now, at least in Octave 6.4.0 on Ubuntu (that's the version currently available in the Ubuntu 22.04 package repository). However, I cannot guarantee that everything will work 100% the same as in MATLAB - I only tested it on a few short audio files.

> How should I run the matlab file? Should I run it using octave-cli in ubuntu?

To run `prepare_data_for_wav2vec` in Octave, either use Octave in interactive mode, like this:

    $ octave
    octave:1> prepare_data_for_wav2vec('/some/path/wav_list_CALLHOME.txt', '/some/path/audio_out', '/some/path/CALLHOME/RTTM', '/some/path/w2v2_ref_VAD_out', 'VAD', 'dataset', 'CALLHOME', 'refFileSuffix', '_RTTM.txt')

Or if you need to call it from another script, this should work:

    octave --eval "prepare_data_for_wav2vec('/some/path/wav_list_CALLHOME.txt', '/some/path/audio_out', '/some/path/CALLHOME/RTTM', '/some/path/w2v2_ref_VAD', 'VAD', 'dataset', 'CALLHOME', 'refFileSuffix', '_RTTM.txt')"

There may be other ways to do it, but like I said, we use MATLAB, so I'm not too familiar with Octave.

> There is a parameter called dir_ref_in in the prepare_data_for_wav2vec.m file, but I don't know which one to put in here. Should I insert a file path in txt format like wavListFile?

`dir_ref_in` is the path to a directory where you have the reference annotation files, in the [RTTM format](https://web.archive.org/web/20170126064326/http://www.itl.nist.gov/iad/mig/tests/rt/2009/docs/rt09-meeting-eval-plan-v2.pdf), 
 (like for speaker diarization). There should be a separate reference file for each WAV file, with a matching name. By default, the script looks for files with a `.rttm` extension, but you can change it to anything else, like in the example above (`'refFileSuffix', '_RTTM.txt'`  will look for files named `<something>_RTTM.txt`")

**Comment by jp1924** [comment]
Thank you for your reply @mkunes!

**Comment by jp1924** [comment]
Thank you for your reply [@mkunes](https://github.com/mkunes)!
I have an additional question.  
This is a question that occurred when I first encountered speaker diarization like VAD.

```
{"path":"/path/CMA01_all.16kHz_t0-30.wav","label": [...]}
{"path":"/path/CMA01_all.16kHz_t30-60.wav","label": [...]}
```

If you look at the file name in the path item here, it says "~t0-30.wav", "~t30-60.wav". Do you cut off voice when doing tasks like VAD or OSD or SCD? Looking at most of the data, there are a lot of voices that go over 20 to 30 minutes, but if you put that voice at once, it takes a lot of load, so are you cutting the voice on purpose? If you cut it, is there a standard for cutting it?
